extends:
    - eslint:recommended
rules:
    no-useless-escape: 1
    eqeqeq: 2
    semi: 2
    quotes:
      - 2
      - double
    dependencies/case-sensitive: 2
    no-console: 0
parserOptions:
    ecmaVersion: 6
    sourceType: module
    ecmaFeatures:
      experimentalObjectRestSpread: true
env:
    node: true
    mocha: true
    es6: true
plugins:
    - dependencies